title: Angel Karentia # your name (or website title) here
logo: "/images/avatars.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  'Colleger - Web Designer - IT Enthusiastic'
  <br><br>
  Interested in learning new things, easily adapt to the new environment, able to work together in teams, multitasking
  <br>
  <a href="https://www.linkedin.com/in/angel-karentia/">View My LinkedIn Profile</a> 
  
#theme: jekyll-theme-minimal
google_analytics: UA-154667908-1 # your Google Analytics tracking ID here
